field_mappings:
  - cortex_field: "alert_id"
    ecs_field: "event.id"
  - cortex_field: "name"
    ecs_field: "event.action"
  - cortex_field: "severity"
    ecs_field: "event.severity"
  - cortex_field: "category"
    ecs_field: "event.category"
  - cortex_field: "source_ip"
    ecs_field: "source.ip"
  - cortex_field: "user_name"
    ecs_field: "user.name"
  - cortex_field: "host_name"
    ecs_field: "host.name"
  - cortex_field: "rule_name"
    ecs_field: "event.rule.name"
  - cortex_field: "description"
    ecs_field: "message"
